blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/sanjeevirajanramajayam/ImageProcessingAPI/discussions
    about: Ask questions, share ideas, and engage with the community.
  - name: 🔒 Security Vulnerability
    url: https://github.com/sanjeevirajanramajayam/ImageProcessingAPI/security/policy
    about: Privately report sensitive security issues.
